[package]
name = "bepinex_gui"
version = "1.0.0"
authors = ["Risk of Thunder"]
license = "MIT"
description = "Graphical User Interface meant to replace the regular console host that is used by BepInEx"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com/xiaoxiao921/egui/", features = ["persistence"] }
serde = { version = "1.0.136", features = ["derive"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
byteorder = "1"
clipboard = "0.5.0"
rand = "0.8.5"
lazy_static = "1.4.0"
directories-next = "2.0.0"
serde_json = "1.0.81"
reqwest = { version = "0.11.10", features = ["blocking", "gzip"] }
sysinfo = "0.23.13"
winapi = {version = "0.3.9", features = ["tlhelp32"] }
strum = { version = "0.24", features = ["derive"] }